name: Release Pull Request

on:
  workflow_call:

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install --no-document git-pr-release
      - continue-on-error: true
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_TEMPLATE: .github/templates/git-pr-release.erb
          TZ: Asia/Tokyo
        run: git-pr-release
      - name: make pull-request to draft
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_JSON=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/pulls?state=open&base=release&head=main")

          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[0].number')
          echo $PR_NUMBER

          gh pr ready --undo $PR_NUMBER
